# Generated by Django 3.2.5 on 2021-08-06 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_post_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 12, 39, 14, 621724)),
        ),
    ]
