# Generated by Django 3.2.5 on 2021-08-06 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20210806_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 12, 45, 21, 437210, tzinfo=utc)),
        ),
    ]
