# Generated by Django 3.2.5 on 2021-08-08 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_post_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 17, 44, 43, 501262, tzinfo=utc)),
        ),
    ]
