# Generated by Django 3.2.5 on 2021-08-08 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20210808_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 18, 5, 21, 471363, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
