# Generated by Django 3.2.5 on 2021-08-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
