# Generated by Django 3.2.5 on 2021-08-02 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210802_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watch_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
