# Generated by Django 3.2.5 on 2021-08-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_watch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watch_list',
            new_name='watching',
        ),
    ]
